### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by 0xCardiE** [IgorShadurin/web3-blog#2]
Cool video and tutorial. Tried it but seems that its not working anymore, build failing at

![image](https://user-images.githubusercontent.com/8969767/208116187-b3ce4e90-581b-4446-a516-16fdcaa3db18.png)

**Comment by IgorShadurin** [comment]
Please re-check. Should be fixed

**Comment by 0xCardiE** [comment]
yes, working now, thx
